application: martin-probst-hrd
version: go
runtime: go
api_version: go1

handlers:
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /.*
  script: _go_app
  login: admin
