application: martin-probst-hrd
version: go
runtime: go
api_version: go1

builtins:
- remote_api: on

default_expiration: "1d"

handlers:
- url: /blog/img
  static_dir: static/img
  expiration: "30d"
- url: /blog/js
  static_dir: static/js
- url: /blog/css
  static_dir: static/css
- url: /.*
  script: _go_app
